osx_image: xcode10.2
language: objective-c
install:
  - ./install_swiftlint.sh
script:
    - |
      xcodebuild clean build test \
      -project FRDIntent.xcodeproj \
      -scheme FRDIntent \
      -sdk iphonesimulator \
      -destination 'platform=iOS Simulator,name=iPhone 5s,OS=12.2' \
      ONLY_ACTIVE_ARCH=NO

    - swiftlint